name: Cache

on:
  push:
    branches: [ master ]

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  NUGET_XMLDOC_MODE: skip
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build projects
      run: dotnet build -c Release -p:RestoreLockedMode=true --verbosity normal
