name: NoCache

on:
  push:
    branches: [ master ]

env:
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build projects
      run: dotnet build -c Release
